#!/usr/bin/perl

use strict;
use warnings;

my @carpet;
my $total;
carpet(2);

foreach my $row(@carpet){
   foreach my $val(@$row){
      print "$val ";
   }
   print "\n";
}

print "Total number of 1's:\t$total\n";

sub carpet {
	my $limit = -1 + 3**shift;
	for my $x (0 .. $limit) {
		for my $y (0 .. $limit) {
			my $result = isPixelFilled($x, $y);
			$carpet[$x][$y] = $result;
			$total += $result;
		}
	}
}

sub isPixelFilled {
	my ($x, $y) = @_;
	
	while($x>0 || $y>0)
    {
        if($x%3==1 && $y%3==1) {
        	return 0;
        }
        $x /= 3;
        $y /= 3;
    }
	return 1;
}
